### ISSUE TITLE
feat: 支持 ASS 转 SRT/BCC

### ISSUE THREAD

**Issue by KimmyXYC** [KimmyXYC/SRT2BCC_TGBot#2]

**Comment by sudoskys** [comment]
以 srt 为中心做支持，这样只需要写逻辑链。
但是可能会损失一些“准确度”？毕竟是多层的。
这是否好？

**Comment by KimmyXYC** [comment]
> 以 srt 为中心做支持，这样只需要写逻辑链。 但是可能会损失一些“准确度”？毕竟是多层的。 这是否好？

没问题 只有 ASS 字幕有具体字体格式及字幕位置信息 其他字幕格式均没有
除BCC字幕格式外 其余字幕格式似乎都支持字幕重叠情况（？）

**Comment by sudoskys** [comment]
#5
